# Most of the code is taken from: https://github.com/grafana/intro-to-foundation-sdk/blob/main/.github/workflows/deploy-dashboard.yml

name: Deploy dashboard
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'amzn'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '9.1.0'
      - name: Java version
        run: java -version\
      - name: Gradle version
        run: gradle -v
      - name: Download and Extract grafanactl
        run: |
          curl -L -o grafanactl-x86_64.tar.gz "https://github.com/grafana/grafanactl/releases/download/${{ vars.GRAFANACTL_VERSION }}/grafanactl_Linux_x86_64.tar.gz"
          tar -xzf grafanactl-x86_64.tar.gz
          chmod +x grafanactl
          sudo mv grafanactl /usr/local/bin/grafanactl
#       Note: since I explicitly include the dashboard JSON in the repo, the build step is not strictly necessary.
#       However, since I don't have CI which checks that the JSON output matches the source in
#       `resources/dashboard.json`, building in CD is necessary.
      - name: Build with Gradle
        run: ./gradlew jar
      - name: Generate dashboard JSON
        run: java -jar dashboard-generator/build/libs/dashboard-generator.jar > resources/dashboard.json
      - name: Deploy Dashboard with grafanactl
        env:
          GRAFANA_SERVER: ${{ vars.GRAFANA_SERVER }}
          GRAFANA_STACK_ID: ${{ vars.GRAFANA_STACK_ID }}
          GRAFANA_TOKEN: ${{ secrets.GRAFANA_TOKEN }}
        run: |
          if [ -f resources/dashboard.json ]; then
            echo "resources/dashboard.json exists, deploying dashboard."
            grafanactl resources push dashboards --path ./resources/dashboard.json
          else
            echo "sample-dashboard.json does not exist."
            exit 1
          fi